# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: units_grpc_stub/conversion_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from units_proto import units_pb2 as units__proto_dot_units__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(units_grpc_stub/conversion_service.proto\x12\x0funits_grpc_stub\x1a\x17units_proto/units.proto2o\n\x15UnitConversionService\x12V\n\x0b\x43onvertUnit\x12\".units_proto.UnitConversionRequest\x1a#.units_proto.UnitConversionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'units_grpc_stub.conversion_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UNITCONVERSIONSERVICE']._serialized_start=86
  _globals['_UNITCONVERSIONSERVICE']._serialized_end=197
# @@protoc_insertion_point(module_scope)
